version: '3'
services:
  bfextractor:
    stdin_open: true
    tty: true
    build: .
    environment:
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      STACKPREFIX: minerva-test
      STAGE: dev
      DEBUG: "True"
    volumes:
      - C:\bfdata:/tmp/aws
    command:
      # Import UUID and also the directory name within /data
      - afterpanel
      # Location of entrypoint within importUuid directory
      - afterpanel.rcpnl
      # Identify for the Bio-Formats Reader, e.g.
      # .rcpnl   -> loci.formats.in.DeltavisionReader
      # .ome.tif -> loci.formats.in.OMETiffReader
      - loci.formats.in.DeltavisionReader
      # Reader Software Name
      - Bio-Formats
      # Reader Software Version
      - UNKNOWN
      # Bucket in which to write tiles
      # Use file:path for writing tiles to local file (for testing purposes)
      - jruokonen-bfextractor-test
      #- file:zarrtest
      # BFU UUID
      - bfuUuid
